// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: shared/proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryCount) Reset() {
	*x = CountryCount{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryCount) ProtoMessage() {}

func (x *CountryCount) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryCount.ProtoReflect.Descriptor instead.
func (*CountryCount) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *CountryCount) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CountryCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BrowserCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Browser       string                 `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserCount) Reset() {
	*x = BrowserCount{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserCount) ProtoMessage() {}

func (x *BrowserCount) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserCount.ProtoReflect.Descriptor instead.
func (*BrowserCount) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *BrowserCount) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *BrowserCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeviceCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCount) Reset() {
	*x = DeviceCount{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCount) ProtoMessage() {}

func (x *DeviceCount) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCount.ProtoReflect.Descriptor instead.
func (*DeviceCount) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceCount) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DailyClickCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // format: "2026-07-08"
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyClickCount) Reset() {
	*x = DailyClickCount{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyClickCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyClickCount) ProtoMessage() {}

func (x *DailyClickCount) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyClickCount.ProtoReflect.Descriptor instead.
func (*DailyClickCount) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DailyClickCount) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyClickCount) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type TopLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Clicks        int64                  `protobuf:"varint,3,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopLink) Reset() {
	*x = TopLink{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopLink) ProtoMessage() {}

func (x *TopLink) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopLink.ProtoReflect.Descriptor instead.
func (*TopLink) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TopLink) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *TopLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *TopLink) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type GetLinkAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"` // "2026-07-01"
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`     // "2026-07-31"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkAnalyticsRequest) Reset() {
	*x = GetLinkAnalyticsRequest{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkAnalyticsRequest) ProtoMessage() {}

func (x *GetLinkAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetLinkAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetLinkAnalyticsRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkAnalyticsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLinkAnalyticsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetLinkAnalyticsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetLinkAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,3,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	TopCountries  []*CountryCount        `protobuf:"bytes,4,rep,name=top_countries,json=topCountries,proto3" json:"top_countries,omitempty"`
	TopBrowsers   []*BrowserCount        `protobuf:"bytes,5,rep,name=top_browsers,json=topBrowsers,proto3" json:"top_browsers,omitempty"`
	TopDevices    []*DeviceCount         `protobuf:"bytes,6,rep,name=top_devices,json=topDevices,proto3" json:"top_devices,omitempty"`
	TimeSeries    []*DailyClickCount     `protobuf:"bytes,7,rep,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkAnalyticsResponse) Reset() {
	*x = GetLinkAnalyticsResponse{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkAnalyticsResponse) ProtoMessage() {}

func (x *GetLinkAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetLinkAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetLinkAnalyticsResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkAnalyticsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetLinkAnalyticsResponse) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *GetLinkAnalyticsResponse) GetTopCountries() []*CountryCount {
	if x != nil {
		return x.TopCountries
	}
	return nil
}

func (x *GetLinkAnalyticsResponse) GetTopBrowsers() []*BrowserCount {
	if x != nil {
		return x.TopBrowsers
	}
	return nil
}

func (x *GetLinkAnalyticsResponse) GetTopDevices() []*DeviceCount {
	if x != nil {
		return x.TopDevices
	}
	return nil
}

func (x *GetLinkAnalyticsResponse) GetTimeSeries() []*DailyClickCount {
	if x != nil {
		return x.TimeSeries
	}
	return nil
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LinkIds       []string               `protobuf:"bytes,2,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // API composition: list link milik user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSummaryRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalLinks    int64                  `protobuf:"varint,1,opt,name=total_links,json=totalLinks,proto3" json:"total_links,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	TopLinks      []*TopLink             `protobuf:"bytes,3,rep,name=top_links,json=topLinks,proto3" json:"top_links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetSummaryResponse) GetTotalLinks() int64 {
	if x != nil {
		return x.TotalLinks
	}
	return 0
}

func (x *GetSummaryResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetSummaryResponse) GetTopLinks() []*TopLink {
	if x != nil {
		return x.TopLinks
	}
	return nil
}

type SubscribeRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LinkIds       []string               `protobuf:"bytes,2,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"` // Filter click events hanya untuk link milik user ini
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRealtimeRequest) Reset() {
	*x = SubscribeRealtimeRequest{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRealtimeRequest) ProtoMessage() {}

func (x *SubscribeRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRealtimeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRealtimeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeRealtimeRequest) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Browser       string                 `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	Device        string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *ClickEvent) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *ClickEvent) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ClickEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ClickEvent) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *ClickEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ClickEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_shared_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_shared_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"&shared/proto/analytics/analytics.proto\x12\tanalytics\">\n" +
	"\fCountryCount\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\">\n" +
	"\fBrowserCount\x12\x18\n" +
	"\abrowser\x18\x01 \x01(\tR\abrowser\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\";\n" +
	"\vDeviceCount\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"=\n" +
	"\x0fDailyClickCount\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\"P\n" +
	"\aTopLink\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06clicks\x18\x03 \x01(\x03R\x06clicks\"o\n" +
	"\x17GetLinkAnalyticsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\"\xeb\x02\n" +
	"\x18GetLinkAnalyticsResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x03 \x01(\x03R\funiqueClicks\x12<\n" +
	"\rtop_countries\x18\x04 \x03(\v2\x17.analytics.CountryCountR\ftopCountries\x12:\n" +
	"\ftop_browsers\x18\x05 \x03(\v2\x17.analytics.BrowserCountR\vtopBrowsers\x127\n" +
	"\vtop_devices\x18\x06 \x03(\v2\x16.analytics.DeviceCountR\n" +
	"topDevices\x12;\n" +
	"\vtime_series\x18\a \x03(\v2\x1a.analytics.DailyClickCountR\n" +
	"timeSeries\"G\n" +
	"\x11GetSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\blink_ids\x18\x02 \x03(\tR\alinkIds\"\x89\x01\n" +
	"\x12GetSummaryResponse\x12\x1f\n" +
	"\vtotal_links\x18\x01 \x01(\x03R\n" +
	"totalLinks\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12/\n" +
	"\ttop_links\x18\x03 \x03(\v2\x12.analytics.TopLinkR\btopLinks\"N\n" +
	"\x18SubscribeRealtimeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\blink_ids\x18\x02 \x03(\tR\alinkIds\"\xa5\x01\n" +
	"\n" +
	"ClickEvent\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x18\n" +
	"\abrowser\x18\x04 \x01(\tR\abrowser\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp2\x8d\x02\n" +
	"\x10AnalyticsService\x12[\n" +
	"\x10GetLinkAnalytics\x12\".analytics.GetLinkAnalyticsRequest\x1a#.analytics.GetLinkAnalyticsResponse\x12I\n" +
	"\n" +
	"GetSummary\x12\x1c.analytics.GetSummaryRequest\x1a\x1d.analytics.GetSummaryResponse\x12Q\n" +
	"\x11SubscribeRealtime\x12#.analytics.SubscribeRealtimeRequest\x1a\x15.analytics.ClickEvent0\x01B?Z=github.com/deaprima/linkforge/services/shared/proto/analyticsb\x06proto3"

var (
	file_shared_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_shared_proto_analytics_analytics_proto_rawDescData []byte
)

func file_shared_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_shared_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_shared_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_analytics_analytics_proto_rawDesc), len(file_shared_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_shared_proto_analytics_analytics_proto_rawDescData
}

var file_shared_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_shared_proto_analytics_analytics_proto_goTypes = []any{
	(*CountryCount)(nil),             // 0: analytics.CountryCount
	(*BrowserCount)(nil),             // 1: analytics.BrowserCount
	(*DeviceCount)(nil),              // 2: analytics.DeviceCount
	(*DailyClickCount)(nil),          // 3: analytics.DailyClickCount
	(*TopLink)(nil),                  // 4: analytics.TopLink
	(*GetLinkAnalyticsRequest)(nil),  // 5: analytics.GetLinkAnalyticsRequest
	(*GetLinkAnalyticsResponse)(nil), // 6: analytics.GetLinkAnalyticsResponse
	(*GetSummaryRequest)(nil),        // 7: analytics.GetSummaryRequest
	(*GetSummaryResponse)(nil),       // 8: analytics.GetSummaryResponse
	(*SubscribeRealtimeRequest)(nil), // 9: analytics.SubscribeRealtimeRequest
	(*ClickEvent)(nil),               // 10: analytics.ClickEvent
}
var file_shared_proto_analytics_analytics_proto_depIdxs = []int32{
	0,  // 0: analytics.GetLinkAnalyticsResponse.top_countries:type_name -> analytics.CountryCount
	1,  // 1: analytics.GetLinkAnalyticsResponse.top_browsers:type_name -> analytics.BrowserCount
	2,  // 2: analytics.GetLinkAnalyticsResponse.top_devices:type_name -> analytics.DeviceCount
	3,  // 3: analytics.GetLinkAnalyticsResponse.time_series:type_name -> analytics.DailyClickCount
	4,  // 4: analytics.GetSummaryResponse.top_links:type_name -> analytics.TopLink
	5,  // 5: analytics.AnalyticsService.GetLinkAnalytics:input_type -> analytics.GetLinkAnalyticsRequest
	7,  // 6: analytics.AnalyticsService.GetSummary:input_type -> analytics.GetSummaryRequest
	9,  // 7: analytics.AnalyticsService.SubscribeRealtime:input_type -> analytics.SubscribeRealtimeRequest
	6,  // 8: analytics.AnalyticsService.GetLinkAnalytics:output_type -> analytics.GetLinkAnalyticsResponse
	8,  // 9: analytics.AnalyticsService.GetSummary:output_type -> analytics.GetSummaryResponse
	10, // 10: analytics.AnalyticsService.SubscribeRealtime:output_type -> analytics.ClickEvent
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_shared_proto_analytics_analytics_proto_init() }
func file_shared_proto_analytics_analytics_proto_init() {
	if File_shared_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_analytics_analytics_proto_rawDesc), len(file_shared_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_shared_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_shared_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_shared_proto_analytics_analytics_proto = out.File
	file_shared_proto_analytics_analytics_proto_goTypes = nil
	file_shared_proto_analytics_analytics_proto_depIdxs = nil
}
