version: '3.8'

services:

  # Postgres
  postgres:
    image: postgres:16-alpine
    container_name: linkforge-postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7-alpine
    container_name: linkforge-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

    # Kafka - KRaft mode
  kafka:
    image: apache/kafka:latest
    container_name: linkforge-kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      # KRaft mode settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
      
      # Listeners (menggunakan dual listener: INTERNAL untuk komunikasi antar container, EXTERNAL untuk host)
      KAFKA_LISTENERS: 'INTERNAL://:29092,CONTROLLER://:29093,EXTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:${KAFKA_PORT}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Q' 
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafkadata:/tmp/kraft-combined-logs
    restart: unless-stopped

  
  # Swagger UI — API Documentation
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: linkforge-swagger
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - ./api/openapi.yml:/tmp/openapi.yml   
    environment:
      SWAGGER_JSON: /tmp/openapi.yml     
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  kafkadata:
