// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: shared/proto/link/link.proto

package link

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,5,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	ClickCount    int64                  `protobuf:"varint,6,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // nullable
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HasPassword   bool                   `protobuf:"varint,10,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_shared_proto_link_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Link) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Link) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Link) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *Link) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *Link) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Link) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`                          // opsional, kosong = auto-generate
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // opsional
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                    // opsional (v1.5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *CreateLinkRequest) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *CreateLinkRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // untuk validasi ownership
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{3}
}

func (x *GetLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{4}
}

func (x *GetLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{5}
}

func (x *ListLinksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListLinksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*Link                `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{6}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"` // opsional
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`                                // opsional
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`       // opsional, null = hapus expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *UpdateLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *UpdateLinkRequest) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type UpdateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // untuk validasi ownership
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLinkRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *DeleteLinkRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ResolveAlias digunakan Gateway untuk mendapatkan URL tujuan saat user mengakses /:alias (public redirect).
type ResolveAliasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAliasRequest) Reset() {
	*x = ResolveAliasRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAliasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAliasRequest) ProtoMessage() {}

func (x *ResolveAliasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAliasRequest.ProtoReflect.Descriptor instead.
func (*ResolveAliasRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveAliasRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type ResolveAliasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	IsExpired     bool                   `protobuf:"varint,3,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`
	HasPassword   bool                   `protobuf:"varint,4,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAliasResponse) Reset() {
	*x = ResolveAliasResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAliasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAliasResponse) ProtoMessage() {}

func (x *ResolveAliasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAliasResponse.ProtoReflect.Descriptor instead.
func (*ResolveAliasResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveAliasResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *ResolveAliasResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ResolveAliasResponse) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

func (x *ResolveAliasResponse) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

type VerifyLinkPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLinkPasswordRequest) Reset() {
	*x = VerifyLinkPasswordRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLinkPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLinkPasswordRequest) ProtoMessage() {}

func (x *VerifyLinkPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLinkPasswordRequest.ProtoReflect.Descriptor instead.
func (*VerifyLinkPasswordRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyLinkPasswordRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *VerifyLinkPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyLinkPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyLinkPasswordResponse) Reset() {
	*x = VerifyLinkPasswordResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyLinkPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyLinkPasswordResponse) ProtoMessage() {}

func (x *VerifyLinkPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyLinkPasswordResponse.ProtoReflect.Descriptor instead.
func (*VerifyLinkPasswordResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyLinkPasswordResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyLinkPasswordResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *VerifyLinkPasswordResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserLinkIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkIDsRequest) Reset() {
	*x = GetUserLinkIDsRequest{}
	mi := &file_shared_proto_link_link_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkIDsRequest) ProtoMessage() {}

func (x *GetUserLinkIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUserLinkIDsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserLinkIDsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserLinkIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkIds       []string               `protobuf:"bytes,1,rep,name=link_ids,json=linkIds,proto3" json:"link_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLinkIDsResponse) Reset() {
	*x = GetUserLinkIDsResponse{}
	mi := &file_shared_proto_link_link_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLinkIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLinkIDsResponse) ProtoMessage() {}

func (x *GetUserLinkIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_link_link_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLinkIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUserLinkIDsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_link_link_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserLinkIDsResponse) GetLinkIds() []string {
	if x != nil {
		return x.LinkIds
	}
	return nil
}

var File_shared_proto_link_link_proto protoreflect.FileDescriptor

const file_shared_proto_link_link_proto_rawDesc = "" +
	"\n" +
	"\x1cshared/proto/link/link.proto\x12\x04link\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x1b\n" +
	"\tshort_url\x18\x05 \x01(\tR\bshortUrl\x12\x1f\n" +
	"\vclick_count\x18\x06 \x01(\x03R\n" +
	"clickCount\x129\n" +
	"\n" +
	"expired_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12!\n" +
	"\fhas_password\x18\n" +
	" \x01(\bR\vhasPassword\"\xbc\x01\n" +
	"\x11CreateLinkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x129\n" +
	"\n" +
	"expired_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"4\n" +
	"\x12CreateLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\"B\n" +
	"\x0eGetLinkRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x0fGetLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\"U\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x11ListLinksResponse\x12 \n" +
	"\x05links\x18\x01 \x03(\v2\n" +
	".link.LinkR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb9\x01\n" +
	"\x11UpdateLinkRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x129\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"4\n" +
	"\x12UpdateLinkResponse\x12\x1e\n" +
	"\x04link\x18\x01 \x01(\v2\n" +
	".link.LinkR\x04link\"E\n" +
	"\x11DeleteLinkRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12DeleteLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x13ResolveAliasRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"\x94\x01\n" +
	"\x14ResolveAliasResponse\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_expired\x18\x03 \x01(\bR\tisExpired\x12!\n" +
	"\fhas_password\x18\x04 \x01(\bR\vhasPassword\"M\n" +
	"\x19VerifyLinkPasswordRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"s\n" +
	"\x1aVerifyLinkPasswordResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12!\n" +
	"\foriginal_url\x18\x03 \x01(\tR\voriginalUrl\"0\n" +
	"\x15GetUserLinkIDsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x16GetUserLinkIDsResponse\x12\x19\n" +
	"\blink_ids\x18\x01 \x03(\tR\alinkIds2\xb3\x04\n" +
	"\vLinkService\x12?\n" +
	"\n" +
	"CreateLink\x12\x17.link.CreateLinkRequest\x1a\x18.link.CreateLinkResponse\x126\n" +
	"\aGetLink\x12\x14.link.GetLinkRequest\x1a\x15.link.GetLinkResponse\x12<\n" +
	"\tListLinks\x12\x16.link.ListLinksRequest\x1a\x17.link.ListLinksResponse\x12?\n" +
	"\n" +
	"UpdateLink\x12\x17.link.UpdateLinkRequest\x1a\x18.link.UpdateLinkResponse\x12?\n" +
	"\n" +
	"DeleteLink\x12\x17.link.DeleteLinkRequest\x1a\x18.link.DeleteLinkResponse\x12E\n" +
	"\fResolveAlias\x12\x19.link.ResolveAliasRequest\x1a\x1a.link.ResolveAliasResponse\x12W\n" +
	"\x12VerifyLinkPassword\x12\x1f.link.VerifyLinkPasswordRequest\x1a .link.VerifyLinkPasswordResponse\x12K\n" +
	"\x0eGetUserLinkIDs\x12\x1b.link.GetUserLinkIDsRequest\x1a\x1c.link.GetUserLinkIDsResponseB:Z8github.com/deaprima/linkforge/services/shared/proto/linkb\x06proto3"

var (
	file_shared_proto_link_link_proto_rawDescOnce sync.Once
	file_shared_proto_link_link_proto_rawDescData []byte
)

func file_shared_proto_link_link_proto_rawDescGZIP() []byte {
	file_shared_proto_link_link_proto_rawDescOnce.Do(func() {
		file_shared_proto_link_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_link_link_proto_rawDesc), len(file_shared_proto_link_link_proto_rawDesc)))
	})
	return file_shared_proto_link_link_proto_rawDescData
}

var file_shared_proto_link_link_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_shared_proto_link_link_proto_goTypes = []any{
	(*Link)(nil),                       // 0: link.Link
	(*CreateLinkRequest)(nil),          // 1: link.CreateLinkRequest
	(*CreateLinkResponse)(nil),         // 2: link.CreateLinkResponse
	(*GetLinkRequest)(nil),             // 3: link.GetLinkRequest
	(*GetLinkResponse)(nil),            // 4: link.GetLinkResponse
	(*ListLinksRequest)(nil),           // 5: link.ListLinksRequest
	(*ListLinksResponse)(nil),          // 6: link.ListLinksResponse
	(*UpdateLinkRequest)(nil),          // 7: link.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),         // 8: link.UpdateLinkResponse
	(*DeleteLinkRequest)(nil),          // 9: link.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),         // 10: link.DeleteLinkResponse
	(*ResolveAliasRequest)(nil),        // 11: link.ResolveAliasRequest
	(*ResolveAliasResponse)(nil),       // 12: link.ResolveAliasResponse
	(*VerifyLinkPasswordRequest)(nil),  // 13: link.VerifyLinkPasswordRequest
	(*VerifyLinkPasswordResponse)(nil), // 14: link.VerifyLinkPasswordResponse
	(*GetUserLinkIDsRequest)(nil),      // 15: link.GetUserLinkIDsRequest
	(*GetUserLinkIDsResponse)(nil),     // 16: link.GetUserLinkIDsResponse
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_shared_proto_link_link_proto_depIdxs = []int32{
	17, // 0: link.Link.expired_at:type_name -> google.protobuf.Timestamp
	17, // 1: link.Link.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: link.Link.updated_at:type_name -> google.protobuf.Timestamp
	17, // 3: link.CreateLinkRequest.expired_at:type_name -> google.protobuf.Timestamp
	0,  // 4: link.CreateLinkResponse.link:type_name -> link.Link
	0,  // 5: link.GetLinkResponse.link:type_name -> link.Link
	0,  // 6: link.ListLinksResponse.links:type_name -> link.Link
	17, // 7: link.UpdateLinkRequest.expired_at:type_name -> google.protobuf.Timestamp
	0,  // 8: link.UpdateLinkResponse.link:type_name -> link.Link
	1,  // 9: link.LinkService.CreateLink:input_type -> link.CreateLinkRequest
	3,  // 10: link.LinkService.GetLink:input_type -> link.GetLinkRequest
	5,  // 11: link.LinkService.ListLinks:input_type -> link.ListLinksRequest
	7,  // 12: link.LinkService.UpdateLink:input_type -> link.UpdateLinkRequest
	9,  // 13: link.LinkService.DeleteLink:input_type -> link.DeleteLinkRequest
	11, // 14: link.LinkService.ResolveAlias:input_type -> link.ResolveAliasRequest
	13, // 15: link.LinkService.VerifyLinkPassword:input_type -> link.VerifyLinkPasswordRequest
	15, // 16: link.LinkService.GetUserLinkIDs:input_type -> link.GetUserLinkIDsRequest
	2,  // 17: link.LinkService.CreateLink:output_type -> link.CreateLinkResponse
	4,  // 18: link.LinkService.GetLink:output_type -> link.GetLinkResponse
	6,  // 19: link.LinkService.ListLinks:output_type -> link.ListLinksResponse
	8,  // 20: link.LinkService.UpdateLink:output_type -> link.UpdateLinkResponse
	10, // 21: link.LinkService.DeleteLink:output_type -> link.DeleteLinkResponse
	12, // 22: link.LinkService.ResolveAlias:output_type -> link.ResolveAliasResponse
	14, // 23: link.LinkService.VerifyLinkPassword:output_type -> link.VerifyLinkPasswordResponse
	16, // 24: link.LinkService.GetUserLinkIDs:output_type -> link.GetUserLinkIDsResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shared_proto_link_link_proto_init() }
func file_shared_proto_link_link_proto_init() {
	if File_shared_proto_link_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_link_link_proto_rawDesc), len(file_shared_proto_link_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_link_link_proto_goTypes,
		DependencyIndexes: file_shared_proto_link_link_proto_depIdxs,
		MessageInfos:      file_shared_proto_link_link_proto_msgTypes,
	}.Build()
	File_shared_proto_link_link_proto = out.File
	file_shared_proto_link_link_proto_goTypes = nil
	file_shared_proto_link_link_proto_depIdxs = nil
}
